import Head from 'next/head';
import Link from 'next/link';
import { storeFront } from '../utils';
import Header from '../components/Header';
import ProductsList from '../components/ProductsList';

export default function IndexPage({ products }) {
	console.log(products.edges[0].node.priceRange.minVariantPrice.amount);
	return (
		<div className=''>
			<Head>
				<title>Shopify and Nextjs</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Header />
			<ProductsList productEdges={products.edges} />
		</div>
	);
}

export const getStaticProps = async () => {
	// Fetch all the products
	const { data } = await storeFront(productsQuery);

	return {
		props: {
			products: data.products,
		},
	};
};

const productsQuery = `
query Products {
  products(first: 6) {
    edges {
      node {
        id
        title
        handle
        tags
        priceRange {
          minVariantPrice {
            amount
          }
        }
        images(first: 1) {
          edges {
            node {
              url
              altText
              id
              src
            }
          }
        }
      }
    }
  }
}
`;
